# Generated by Django 5.2.7 on 2025-11-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartmargin', '0002_rename_quanitity_productingredient_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profit_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='profit_margin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_cost',
        ),
    ]
