# Generated by Django 5.2.7 on 2025-11-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmargin', '0003_remove_product_profit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='product',
            name='profit_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_percentage',
            field=models.FloatField(default=30),
        ),
    ]
