# Generated by Django 5.2.7 on 2025-11-04 09:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmargin', '0004_remove_product_created_remove_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
