# Generated by Django 5.2.7 on 2025-11-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmargin', '0005_alter_product_profit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='content',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='title',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
