# Generated by Django 5.2.7 on 2025-11-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartmargin', '0006_remove_dashboard_content_remove_dashboard_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
